### ISSUE TITLE
Keyboard does not include the change of capslock to backspace

### ISSUE THREAD

**Issue by Bryntet** [motform/colemak-se#2]

**Comment by motform** [comment]
Hi @augustuslego,

This is intentional, as the mapping from `caps` to `backspace` is a bit... contentious? In my experience it is far more common to remap caps to either `esc` or `ctrl` (or both, as per the "space cadet" style that I prefer). Regardless of what you prefer, I think it makes more sense to leave `caps` untouched, as at least [macOS](https://coderwall.com/p/cq_lkg/remapping-caps-lock-key-to-something-more-natural-on-mac-os-x) features builtin remapping (I would also assume that leaving it `caps` and not logical `backspace` would make it easier to remap in Windows, where you have to change a value in the registry afaik).

**Comment by Bryntet** [comment]
Thanks for your response! I completely see what you mean and I'll try to find a solution using the registry in windows

**Comment by motform** [comment]
Microsoft actually have GUI support for this type of modification nowadays, sort of. It is part of the strange, but seemingly useful, bag of stuff found in [Power Toys](https://docs.microsoft.com/en-us/windows/powertoys/). I'll complete this issue and update the readme with pointers to this.
